name: Documentation Build

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  DocsBuild:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/docs_build_template.yml@feature/ifs-5030-test-git-lfs-production
    secrets:
      ANTORA_TRIGGER_TOKEN: ${{ secrets.ANTORA_TRIGGER_TOKEN }}
